### ISSUE TITLE
想单独使用改造 @mpflow/wxml-loader @mpflow/wxss-loader 来达到 wxml wxss class rename 的效果

### ISSUE THREAD

**Issue by sonofmagic** [wechat-miniprogram/mpflow#13]
wxml 对 class 的限制很多，比如不能用 [,] ,\,/ 这类符号，我想让用户写的时候可以 w-[100px]，然后再打包时，被无感知的替换。

另外 `mpflow` 居然是微信的官方项目，也是很欣喜啊。

**Comment by Tidyzq** [comment]
@mpflow/wxml-loader 的作用仅仅为让 webpack 能够正确读取 wxml。你这里的场景应该需要的是一个 preprocessor 在 @mpflow/wxml-loader 之前做处理

**Comment by sonofmagic** [comment]
好的
