### ISSUE TITLE
引用同一个npm包内的js以及小程序组件导致构建报错

### ISSUE THREAD

**Issue by ThenMorning** [wechat-miniprogram/mpflow#18]
如：
在A组件的js中
import * as Vap from '@lingbo/effects-mini';
在B组件的json中
"vap": "@lingbo/effects-mini/miniprogram_dist/vap/vap"

会报错：
<img width="676" alt="截屏2023-08-29 16 03 11" src="https://github.com/wechat-miniprogram/mpflow/assets/22017926/feb60339-1c49-4ab4-8318-5e3a4b777b70">
，去掉A组件中的引用就不报错了

求尽快修复

**Comment by Tidyzq** [comment]
请提供一个最小复现

**Comment by ThenMorning** [comment]
不好意思，已经通过代码片段发现，是依赖的npm包导出问题

发自我的 iPhone

在 2023年8月29日，16:46，Tidyzq ***@***.***> 写道：

﻿

请提供一个最小复现
