### ISSUE TITLE
结合 vant-weapp 使用时，wxs 的打包有问题

### ISSUE THREAD

**Issue by heroicyang** [wechat-miniprogram/mpflow#4]
- 首先是 wxs src 只能用[相对路径](https://developers.weixin.qq.com/miniprogram/dev/reference/wxs/01wxs-module.html)，但现在打包后是绝对路径

![image](https://user-images.githubusercontent.com/949427/103003109-1f11a780-456b-11eb-9a09-f2817dce40e8.png)

![image](https://user-images.githubusercontent.com/949427/103003126-2933a600-456b-11eb-87e4-44f0b8884939.png)

- 其次是如果一个 wxs 里有 require 其它 wxs，在打包时并没有将 require 的也打包进去，_commons 目录下并没有其它的 wxs 文件
![image](https://user-images.githubusercontent.com/949427/103003205-541dfa00-456b-11eb-94ea-9d11b053d4f4.png)

**Comment by Tidyzq** [comment]
问题1：更新最新的小程序开发者工具
问题2：这个确实还没支持，还在考虑合适的实现方案

**Comment by heroicyang** [comment]
好的，多谢。我暂时把 vant-weapp/dist 整个拷贝进项目，然后自定义`configureWebpackChain`来实现了打包，期待 mpflow 的改进，挺好用的。
